const assets = [
    {
        "ID": "REF-CEL-001",
        "Tipo": "Smartphone",
        "Modelo/Marca": "Samsung Galaxy A15 5G",
        "Número de série": "RQCX40AANRL",
        "Aquisição": "",
        "Usuário Responsável": "Adriana Ribeiro",
        "Localização": "Adm",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Bom",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-CEL-002",
        "Tipo": "Smartphone",
        "Modelo/Marca": "Samsung Galaxy A05",
        "Número de série": "R9XX301WP4D",
        "Aquisição": "",
        "Usuário Responsável": "Erivane do Carmo",
        "Localização": "Adm",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Bom",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-CEL-003",
        "Tipo": "Smartphone",
        "Modelo/Marca": "Xiaomi Redmi A2",
        "Número de série": "23026RN54G",
        "Aquisição": "",
        "Usuário Responsável": "Adriana Ribeiro",
        "Localização": "Adm",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Bom",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-CEL-004",
        "Tipo": "Smartphone",
        "Modelo/Marca": "Samsung Galaxy A04e",
        "Número de série": "R9QWB0254FJ",
        "Aquisição": "",
        "Usuário Responsável": "",
        "Localização": "Adm",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Bom",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-CEL-005",
        "Tipo": "Smartphone",
        "Modelo/Marca": "Samsung Galaxy A12",
        "Número de série": "RX8R108C6AF",
        "Aquisição": "",
        "Usuário Responsável": "Weverton Oliveira",
        "Localização": "Adm",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Bom",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-IM-001",
        "Tipo": "Impressora",
        "Modelo/Marca": "Brother DCP L2540DW",
        "Número de série": "N/A",
        "Aquisição": "1/13/22",
        "Usuário Responsável": "Weverton Oliveira",
        "Localização": "Caixa",
        "Endereço IP": "192.168.0.25",
        "Status": "Ativo",
        "Valor": " R$ 2,699.00 ",
        "Estado do equipamento": "Ruim",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": "Necessita de manutenção e limpeza"
    },
    {
        "ID": "REF-IM-002",
        "Tipo": "Impressora",
        "Modelo/Marca": "Brother DCP 8152DN",
        "Número de série": "N/A",
        "Aquisição": "N/A",
        "Usuário Responsável": "Weverton Oliveira",
        "Localização": "Televendas",
        "Endereço IP": "192.168.0.30",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Regular",
        "Última manutenção": "Sep-24",
        "Garantia": "Não possui",
        "Observações": "Está temporareamente alocada \nno vendas"
    },
    {
        "ID": "REF-IM-003",
        "Tipo": "Impressora",
        "Modelo/Marca": "Epson L4260",
        "Número de série": "N/A",
        "Aquisição": "Sep-24",
        "Usuário Responsável": "Weverton Oliveira",
        "Localização": "Adm",
        "Endereço IP": "Compart.",
        "Status": "Ativo",
        "Valor": " R$ 1,299.00 ",
        "Estado do equipamento": "Bom",
        "Última manutenção": "-",
        "Garantia": "3 meses",
        "Observações": ""
    },
    {
        "ID": "REF-IME-000",
        "Tipo": "Impressora de Etiqueta",
        "Modelo/Marca": "Argox OS 214 Plus",
        "Número de série": "",
        "Aquisição": "",
        "Usuário Responsável": "Misael",
        "Localização": "Estoque",
        "Endereço IP": "Local",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Bom",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-IME-001",
        "Tipo": "Impressora de Etiqueta",
        "Modelo/Marca": "Elgin L42 Pro",
        "Número de série": "6700",
        "Aquisição": "6/27/24",
        "Usuário Responsável": "Rodrigo Teixeira",
        "Localização": "Estoque",
        "Endereço IP": "Local",
        "Status": "Ativo",
        "Valor": " R$ 1,299.00 ",
        "Estado do equipamento": "Regular",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-IMT-001",
        "Tipo": "Impressora Térmica",
        "Modelo/Marca": "Elgin MP 4200 HS",
        "Número de série": "N/A",
        "Aquisição": "1/5/24",
        "Usuário Responsável": "Rodrigo Teixeira",
        "Localização": "Estoque",
        "Endereço IP": "192.168.0.252",
        "Status": "Ativo",
        "Valor": " R$ 1,299.00 ",
        "Estado do equipamento": "Bom",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-IMT-002",
        "Tipo": "Impressora Térmica",
        "Modelo/Marca": "Elgin i9 Full",
        "Número de série": "6954",
        "Aquisição": "1/5/24",
        "Usuário Responsável": "Paulo Emílio",
        "Localização": "Estoque",
        "Endereço IP": "192.168.0.208",
        "Status": "Ativo",
        "Valor": " R$ 680.00 ",
        "Estado do equipamento": "Bom",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-MO-001",
        "Tipo": "Monitor",
        "Modelo/Marca": "HQ Screen 19.5\"\" LED",
        "Número de série": "195HQLED175507234966",
        "Aquisição": "",
        "Usuário Responsável": "Weverton Oliveira",
        "Localização": "Adm",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Ruim",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": "Está queimando os pixels"
    },
    {
        "ID": "REF-MO-002",
        "Tipo": "Monitor",
        "Modelo/Marca": "HQ Screen 19.5\"\" LED",
        "Número de série": "195H0LED175507235230",
        "Aquisição": "",
        "Usuário Responsável": "Weverton Oliveira",
        "Localização": "Adm",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Regular",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-MO-003",
        "Tipo": "Monitor",
        "Modelo/Marca": "HQ Screen 19.5\"\" LED",
        "Número de série": "1953GLED1853122319568",
        "Aquisição": "",
        "Usuário Responsável": "Jeferson",
        "Localização": "Adm",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Regular",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-MO-004",
        "Tipo": "Monitor",
        "Modelo/Marca": "3Green 19.5\"\" LED",
        "Número de série": "1953GLED1907042401584",
        "Aquisição": "",
        "Usuário Responsável": "Adriana",
        "Localização": "Adm",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Regular",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-MO-005",
        "Tipo": "Monitor",
        "Modelo/Marca": "HQ Screen 19.5\"\" LED",
        "Número de série": "195HQLED158408221848",
        "Aquisição": "",
        "Usuário Responsável": "Adriana",
        "Localização": "Adm",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Regular",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-MO-006",
        "Tipo": "Monitor",
        "Modelo/Marca": "HQ Screen 19.5\"\" LED",
        "Número de série": "195HQLED173607235914",
        "Aquisição": "",
        "Usuário Responsável": "Adriana",
        "Localização": "Adm",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Regular",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-MO-007",
        "Tipo": "Monitor",
        "Modelo/Marca": "HQ Screen 19.5\"\" LED",
        "Número de série": "195HQLED1563072210366",
        "Aquisição": "",
        "Usuário Responsável": "Adriana",
        "Localização": "Adm",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Regular",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-MO-008",
        "Tipo": "Monitor",
        "Modelo/Marca": "HQ Screen 19.5\"\" LED",
        "Número de série": "195HQLED163011220442",
        "Aquisição": "",
        "Usuário Responsável": "Fabiana",
        "Localização": "Adm",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Regular",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-MO-009",
        "Tipo": "Monitor",
        "Modelo/Marca": "HQ Screen 19.5\"\" LED",
        "Número de série": "195HQLED1563072210370",
        "Aquisição": "",
        "Usuário Responsável": "Fabiana",
        "Localização": "Adm",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Regular",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-MO-010",
        "Tipo": "Monitor",
        "Modelo/Marca": "3Green 19.5\"\" LED",
        "Número de série": "1953GLED180209230360",
        "Aquisição": "",
        "Usuário Responsável": "Erivane do Carmo",
        "Localização": "Adm",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Regular",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-MO-011",
        "Tipo": "Monitor",
        "Modelo/Marca": "HQ Screen 19.5\"\" LED",
        "Número de série": "195HQLED1425092105065",
        "Aquisição": "",
        "Usuário Responsável": "Erivane do Carmo",
        "Localização": "Adm",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Regular",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-MO-012",
        "Tipo": "Monitor",
        "Modelo/Marca": "3Green 19.5\"\" LED",
        "Número de série": "1953GLED1853122305390",
        "Aquisição": "",
        "Usuário Responsável": "Fabiana",
        "Localização": "Adm",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Regular",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-MO-013",
        "Tipo": "Monitor",
        "Modelo/Marca": "HQ Screen 19.5\"\" LED",
        "Número de série": "195HQLED1425092105065",
        "Aquisição": "",
        "Usuário Responsável": "Fabiana",
        "Localização": "Adm",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Regular",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-MO-014",
        "Tipo": "Monitor",
        "Modelo/Marca": "HQ Screen 19.5\"\" LED",
        "Número de série": "195HQLED159910223739",
        "Aquisição": "",
        "Usuário Responsável": "Luiza",
        "Localização": "Adm",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Regular",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-MO-015",
        "Tipo": "Monitor",
        "Modelo/Marca": "HQ Screen 19.5\"\" LED",
        "Número de série": "195HQLED163011220805",
        "Aquisição": "",
        "Usuário Responsável": "Maicon Azevedo",
        "Localização": "Adm",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Regular",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-MO-016",
        "Tipo": "Monitor",
        "Modelo/Marca": "3Green 19.5\"\" LED",
        "Número de série": "1953GLED1853122307598",
        "Aquisição": "",
        "Usuário Responsável": "Maicon Azevedo",
        "Localização": "Adm",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Regular",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-MO-017",
        "Tipo": "Monitor",
        "Modelo/Marca": "HQ Screen 19.5\"\" LED",
        "Número de série": "195HQLED173607235649",
        "Aquisição": "",
        "Usuário Responsável": "Misael",
        "Localização": "Recebimento",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Regular",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-MO-018",
        "Tipo": "Monitor",
        "Modelo/Marca": "HQ Screen 19.5\"\" LED",
        "Número de série": "195HQLED173607236024",
        "Aquisição": "",
        "Usuário Responsável": "Rodrigo Teixeira",
        "Localização": "Transporte",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Regular",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-MO-019",
        "Tipo": "Monitor",
        "Modelo/Marca": "3Green 19.5\"\" LED",
        "Número de série": "DF19175508230128",
        "Aquisição": "",
        "Usuário Responsável": "Separador",
        "Localização": "Separação",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Regular",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-MO-020",
        "Tipo": "Monitor",
        "Modelo/Marca": "HQ Screen 19.5\"\" LED",
        "Número de série": "195HQLED1471112100957",
        "Aquisição": "",
        "Usuário Responsável": "Julio",
        "Localização": "Separação",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Regular",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-MO-021",
        "Tipo": "Monitor",
        "Modelo/Marca": "HQ Screen 19.5\"\" LED",
        "Número de série": "195HOLED159909221223",
        "Aquisição": "",
        "Usuário Responsável": "Paulo Emílio",
        "Localização": "Expedição",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Regular",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-MO-022",
        "Tipo": "Monitor",
        "Modelo/Marca": "3Green 19.5\"\" LED",
        "Número de série": "1953GLED1907042400261",
        "Aquisição": "",
        "Usuário Responsável": "Paulo Emílio",
        "Localização": "Expedição",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Regular",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-MO-023",
        "Tipo": "Monitor",
        "Modelo/Marca": "3Green 19.5\"\" LED",
        "Número de série": "1953GLED1907042401587",
        "Aquisição": "",
        "Usuário Responsável": "Vander",
        "Localização": "Garantia",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Regular",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-MO-024",
        "Tipo": "Monitor",
        "Modelo/Marca": "3Green 19.5\"\" LED",
        "Número de série": "1953GLED1907042401563",
        "Aquisição": "",
        "Usuário Responsável": "Vander",
        "Localização": "Garantia",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Regular",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-MO-025",
        "Tipo": "Monitor",
        "Modelo/Marca": "3Green 19.5\"\" LED",
        "Número de série": "1953GLED1907042401598",
        "Aquisição": "",
        "Usuário Responsável": "Anderson Bugai",
        "Localização": "Televendas",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Regular",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-MO-026",
        "Tipo": "Monitor",
        "Modelo/Marca": "HQ Screen 19.5\"\" LED",
        "Número de série": "195HQLED1471112100958",
        "Aquisição": "",
        "Usuário Responsável": "Robson",
        "Localização": "Televendas",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Regular",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-MO-027",
        "Tipo": "Monitor",
        "Modelo/Marca": "HQ Screen 19.5\"\" LED",
        "Número de série": "N/A",
        "Aquisição": "",
        "Usuário Responsável": "",
        "Localização": "Televendas",
        "Endereço IP": "",
        "Status": "Inativo",
        "Valor": "",
        "Estado do equipamento": "Ruim",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-MO-028",
        "Tipo": "Monitor",
        "Modelo/Marca": "HQ Screen 19.5\"\" LED",
        "Número de série": "195HQLED1425092105062",
        "Aquisição": "",
        "Usuário Responsável": "Tales",
        "Localização": "Televendas",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Bom",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-MO-029",
        "Tipo": "Monitor",
        "Modelo/Marca": "HQ Screen 24\"\" LED",
        "Número de série": "WD202214NN22",
        "Aquisição": "",
        "Usuário Responsável": "Rubens",
        "Localização": "Televendas",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Bom",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-MO-030",
        "Tipo": "Monitor",
        "Modelo/Marca": "3Green 19.5\"\" LED",
        "Número de série": "1953GLED1907042403408",
        "Aquisição": "",
        "Usuário Responsável": "Rubens",
        "Localização": "Televendas",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Bom",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-MO-031",
        "Tipo": "Monitor",
        "Modelo/Marca": "3Green 19.5\"\" LED",
        "Número de série": "1953GLED1907042401538",
        "Aquisição": "",
        "Usuário Responsável": "Renato",
        "Localização": "Televendas",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Bom",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-MO-032",
        "Tipo": "Monitor",
        "Modelo/Marca": "HQ Screen 24\"\" LED",
        "Número de série": "195H0LED158408220408",
        "Aquisição": "",
        "Usuário Responsável": "Higor",
        "Localização": "Televendas",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Bom",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-MO-033",
        "Tipo": "Monitor",
        "Modelo/Marca": "HQ Screen 24\"\" LED",
        "Número de série": "195HQLED173607235761",
        "Aquisição": "",
        "Usuário Responsável": "Juliano",
        "Localização": "Televendas",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Bom",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-MO-034",
        "Tipo": "Monitor",
        "Modelo/Marca": "HQ Screen 24\"\" LED",
        "Número de série": "195H0LED158408221850",
        "Aquisição": "",
        "Usuário Responsável": "Amaro",
        "Localização": "Televendas",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Bom",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-MO-035",
        "Tipo": "Monitor",
        "Modelo/Marca": "HQ Screen 24\"\" LED",
        "Número de série": "195HQLED175507235517",
        "Aquisição": "",
        "Usuário Responsável": "Paulo Sérgio",
        "Localização": "Televendas",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Bom",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-MO-036",
        "Tipo": "Monitor",
        "Modelo/Marca": "3Green 19.5\"\" LED",
        "Número de série": "1953GLED1907042403434",
        "Aquisição": "",
        "Usuário Responsável": "Warley",
        "Localização": "Televendas",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Bom",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-MO-037",
        "Tipo": "Monitor",
        "Modelo/Marca": "3Green 19.5\"\" LED",
        "Número de série": "1953GLED1907042401607",
        "Aquisição": "",
        "Usuário Responsável": "Weverton Oliveira",
        "Localização": "Caixa",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Bom",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-MO-038",
        "Tipo": "Monitor",
        "Modelo/Marca": "3Green 19.5\"\" LED",
        "Número de série": "1953GLED1853122305413",
        "Aquisição": "",
        "Usuário Responsável": "Weverton Oliveira",
        "Localização": "Caixa",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Bom",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-MO-039",
        "Tipo": "Monitor",
        "Modelo/Marca": "3Green 19.5\"\" LED",
        "Número de série": "1953GLED1907042400260",
        "Aquisição": "",
        "Usuário Responsável": "Nicole",
        "Localização": "Caixa",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Bom",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-MO-040",
        "Tipo": "Monitor",
        "Modelo/Marca": "HQ Screen 24\"\" LED",
        "Número de série": "195HQLED1471122108559",
        "Aquisição": "",
        "Usuário Responsável": "Lorena",
        "Localização": "Caixa",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Bom",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-MO-041",
        "Tipo": "Monitor",
        "Modelo/Marca": "3Green 19.5\"\" LED",
        "Número de série": "1953GLED180209230359",
        "Aquisição": "",
        "Usuário Responsável": "Evandro",
        "Localização": "Balcão",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Bom",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-MO-042",
        "Tipo": "Monitor",
        "Modelo/Marca": "HQ Screen 24\"\" LED",
        "Número de série": "195HOLED158408221849",
        "Aquisição": "",
        "Usuário Responsável": "Jonathan",
        "Localização": "Balcão",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Bom",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-MO-043",
        "Tipo": "Monitor",
        "Modelo/Marca": "HQ Screen 24\"\" LED",
        "Número de série": "195HQLED1425092105063",
        "Aquisição": "",
        "Usuário Responsável": "Gabriel",
        "Localização": "Balcão",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Bom",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-MO-044",
        "Tipo": "Monitor",
        "Modelo/Marca": "HQ Screen 24\"\" LED",
        "Número de série": "195HQLED159910223738",
        "Aquisição": "",
        "Usuário Responsável": "Luan",
        "Localização": "Balcão",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Bom",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-MO-045",
        "Tipo": "Monitor",
        "Modelo/Marca": "HQ Screen 24\"\" LED",
        "Número de série": "195HQLED1563072210369",
        "Aquisição": "",
        "Usuário Responsável": "Calixton",
        "Localização": "Balcão",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Bom",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-MO-046",
        "Tipo": "Monitor",
        "Modelo/Marca": "3Green 19.5\"\" LED",
        "Número de série": "DF19175508233830",
        "Aquisição": "",
        "Usuário Responsável": "Anderson",
        "Localização": "Balcão",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Bom",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-MO-047",
        "Tipo": "Monitor",
        "Modelo/Marca": "3Green 19.5\"\" LED",
        "Número de série": "195H0LED163011220192",
        "Aquisição": "",
        "Usuário Responsável": "Juliano",
        "Localização": "Diretoria",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Bom",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-MO-048",
        "Tipo": "Monitor",
        "Modelo/Marca": "3Green 19.5\"\" LED",
        "Número de série": "1953GLED1907042401543",
        "Aquisição": "",
        "Usuário Responsável": "Juliano",
        "Localização": "Diretoria",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Bom",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-NB-001",
        "Tipo": "Nobreak",
        "Modelo/Marca": "Intelbras 1200VA",
        "Número de série": "N/A",
        "Aquisição": "N/A",
        "Usuário Responsável": "Weverton Oliveira",
        "Localização": "Adm",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Bom",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": "Alimentando o rack de rede"
    },
    {
        "ID": "REF-NB-002",
        "Tipo": "Nobreak",
        "Modelo/Marca": "UPS Mini 600VA",
        "Número de série": "N/A",
        "Aquisição": "N/A",
        "Usuário Responsável": "Weverton Oliveira",
        "Localização": "Adm",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Regular",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": "Bateria não está suportando carga"
    },
    {
        "ID": "REF-PC-001",
        "Tipo": "Computador",
        "Modelo/Marca": "Bel Micro i5-3570 12GB",
        "Número de série": "N/A",
        "Aquisição": "N/A",
        "Usuário Responsável": "Weverton Oliveira",
        "Localização": "Adm",
        "Endereço IP": "192.168.0.77",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Bom",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-PC-002",
        "Tipo": "Computador",
        "Modelo/Marca": "Bel Micro i5-2400 16GB",
        "Número de série": "N/A",
        "Aquisição": "N/A",
        "Usuário Responsável": "Erivane do Carmo",
        "Localização": "Adm",
        "Endereço IP": "192.168.0.28",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Bom",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-PC-003",
        "Tipo": "Computador",
        "Modelo/Marca": "Bel Micro i5-3470 16GB",
        "Número de série": "N/A",
        "Aquisição": "N/A",
        "Usuário Responsável": "Luiza",
        "Localização": "Adm",
        "Endereço IP": "192.168.0.76",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Regular",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-PC-004",
        "Tipo": "Computador",
        "Modelo/Marca": "Bel Micro i5-2400 8GB",
        "Número de série": "N/A",
        "Aquisição": "N/A",
        "Usuário Responsável": "Fabiana",
        "Localização": "Adm",
        "Endereço IP": "192.168.0.68",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Regular",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-PC-005",
        "Tipo": "Computador",
        "Modelo/Marca": "Bel Micro i5-2400 8GB",
        "Número de série": "N/A",
        "Aquisição": "N/A",
        "Usuário Responsável": "Não alocado",
        "Localização": "Adm",
        "Endereço IP": "192.168.0.36",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Bom",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-PC-006",
        "Tipo": "Computador",
        "Modelo/Marca": "Bel Micro i7-2600 4GB",
        "Número de série": "N/A",
        "Aquisição": "N/A",
        "Usuário Responsável": "Adriana",
        "Localização": "Adm",
        "Endereço IP": "192.168.0.55",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Ruim",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": "Placa de áudio não funcionando"
    },
    {
        "ID": "REF-PC-007",
        "Tipo": "Computador",
        "Modelo/Marca": "Bel Micro i5-2600 16GB",
        "Número de série": "N/A",
        "Aquisição": "N/A",
        "Usuário Responsável": "Jeferson",
        "Localização": "Adm",
        "Endereço IP": "192.168.0.20",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Regular",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-PC-008",
        "Tipo": "Computador",
        "Modelo/Marca": "Bel Micro i7-2600 4GB",
        "Número de série": "N/A",
        "Aquisição": "N/A",
        "Usuário Responsável": "Claudio",
        "Localização": "Adm",
        "Endereço IP": "192.168.0.8",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Bom",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-PC-009",
        "Tipo": "Computador",
        "Modelo/Marca": "Bel Micro i5-4570 8GB",
        "Número de série": "N/A",
        "Aquisição": "N/A",
        "Usuário Responsável": "Evandro",
        "Localização": "Balcão",
        "Endereço IP": "192.168.0.74",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Regular",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-PC-010",
        "Tipo": "Computador",
        "Modelo/Marca": "Bel Micro i5-4590 8GB",
        "Número de série": "N/A",
        "Aquisição": "N/A",
        "Usuário Responsável": "Gabriel",
        "Localização": "Balcão",
        "Endereço IP": "192.168.0.59",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Regular",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-PC-011",
        "Tipo": "Computador",
        "Modelo/Marca": "Bel Micro i5-4570 8GB",
        "Número de série": "N/A",
        "Aquisição": "N/A",
        "Usuário Responsável": "Jonathan",
        "Localização": "Balcão",
        "Endereço IP": "192.168.0.41",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Regular",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-PC-012",
        "Tipo": "Computador",
        "Modelo/Marca": "Bel Micro i5-4580 8GB",
        "Número de série": "N/A",
        "Aquisição": "N/A",
        "Usuário Responsável": "Luan",
        "Localização": "Balcão",
        "Endereço IP": "192.168.0.34",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Regular",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-PC-013",
        "Tipo": "Computador",
        "Modelo/Marca": "Bel Micro i5-2400 8GB",
        "Número de série": "N/A",
        "Aquisição": "N/A",
        "Usuário Responsável": "Cleber",
        "Localização": "Balcão",
        "Endereço IP": "192.168.0.35",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Regular",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-PC-014",
        "Tipo": "Computador",
        "Modelo/Marca": "Bel Micro AMD Athlon 3000G 8GB",
        "Número de série": "N/A",
        "Aquisição": "N/A",
        "Usuário Responsável": "Calixton",
        "Localização": "Balcão",
        "Endereço IP": "192.168.0.2",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Regular",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-PC-015",
        "Tipo": "Computador",
        "Modelo/Marca": "Bel Micro i5-2400 16GB",
        "Número de série": "N/A",
        "Aquisição": "N/A",
        "Usuário Responsável": "Anderson",
        "Localização": "Balcão",
        "Endereço IP": "192.168.0.3",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Regular",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-PC-016",
        "Tipo": "Computador",
        "Modelo/Marca": "Bel Micro i5-2400 8GB",
        "Número de série": "N/A",
        "Aquisição": "N/A",
        "Usuário Responsável": "Paulo Emílio",
        "Localização": "Expedição",
        "Endereço IP": "192.168.0.37",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Bom",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-PC-017",
        "Tipo": "Computador",
        "Modelo/Marca": "Bel Micro i5-2600 8GB",
        "Número de série": "N/A",
        "Aquisição": "N/A",
        "Usuário Responsável": "Paulo Emílio",
        "Localização": "Expedição",
        "Endereço IP": "192.168.0.16",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Bom",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-PC-018",
        "Tipo": "Computador",
        "Modelo/Marca": "Bel Micro AMD Athlon 3000G 8GB",
        "Número de série": "N/A",
        "Aquisição": "N/A",
        "Usuário Responsável": "Vander",
        "Localização": "Garantia",
        "Endereço IP": "192.168.0.56",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Regular",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-PC-019",
        "Tipo": "Computador",
        "Modelo/Marca": "Bel Micro AMD Athlon 3000G 8GB",
        "Número de série": "N/A",
        "Aquisição": "N/A",
        "Usuário Responsável": "Vander",
        "Localização": "Garantia",
        "Endereço IP": "192.168.0.33",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Regular",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-PC-020",
        "Tipo": "Computador",
        "Modelo/Marca": "Bel Micro i5-2400 8GB",
        "Número de série": "N/A",
        "Aquisição": "N/A",
        "Usuário Responsável": "Anderson Bugai",
        "Localização": "Televendas",
        "Endereço IP": "192.168.0.53",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Bom",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-PC-021",
        "Tipo": "Computador",
        "Modelo/Marca": "Bel Micro i5-2400 16GB",
        "Número de série": "N/A",
        "Aquisição": "N/A",
        "Usuário Responsável": "Robson",
        "Localização": "Televendas",
        "Endereço IP": "192.168.0.39",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Bom",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-PC-022",
        "Tipo": "Computador",
        "Modelo/Marca": "Bel Micro i5-2400 16GB",
        "Número de série": "N/A",
        "Aquisição": "N/A",
        "Usuário Responsável": "Warley",
        "Localização": "Televendas",
        "Endereço IP": "192.168.0.24",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Bom",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-PC-023",
        "Tipo": "Computador",
        "Modelo/Marca": "Bel Micro i7 3770 12GB",
        "Número de série": "N/A",
        "Aquisição": "N/A",
        "Usuário Responsável": "Rubens",
        "Localização": "Televendas",
        "Endereço IP": "192.168.0.49",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Bom",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-PC-024",
        "Tipo": "Computador",
        "Modelo/Marca": "Bel Micro i7 3770 4GB",
        "Número de série": "N/A",
        "Aquisição": "N/A",
        "Usuário Responsável": "Tales",
        "Localização": "Televendas",
        "Endereço IP": "192.168.0.72",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Bom",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-PC-025",
        "Tipo": "Computador",
        "Modelo/Marca": "Bel Micro i5 4670 8GB",
        "Número de série": "N/A",
        "Aquisição": "N/A",
        "Usuário Responsável": "Renato",
        "Localização": "Televendas",
        "Endereço IP": "192.168.0.6",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Bom",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-PC-026",
        "Tipo": "Computador",
        "Modelo/Marca": "Bel Micro i5 2400 8GB",
        "Número de série": "N/A",
        "Aquisição": "N/A",
        "Usuário Responsável": "Igor",
        "Localização": "Televendas",
        "Endereço IP": "192.168.0.21",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Bom",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": "Necessita ativação do Windows"
    },
    {
        "ID": "REF-PC-027",
        "Tipo": "Computador",
        "Modelo/Marca": "Bel Micro i5 3300 8GB",
        "Número de série": "N/A",
        "Aquisição": "N/A",
        "Usuário Responsável": "Supervisor Vendas",
        "Localização": "Televendas",
        "Endereço IP": "192.168.0.60",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Bom",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-PC-028",
        "Tipo": "Computador",
        "Modelo/Marca": "Bel Micro i7 2600 4GB",
        "Número de série": "N/A",
        "Aquisição": "N/A",
        "Usuário Responsável": "Paulo Sérgio",
        "Localização": "Televendas",
        "Endereço IP": "192.168.0.57",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Bom",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-PC-029",
        "Tipo": "Computador",
        "Modelo/Marca": "Bel Micro i5 8GB",
        "Número de série": "N/A",
        "Aquisição": "N/A",
        "Usuário Responsável": "Amaro",
        "Localização": "Televendas",
        "Endereço IP": "192.168.0.64",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Bom",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": "Não possui modelo do processador cadastrado. Necessita ativação do windows"
    },
    {
        "ID": "REF-PC-030",
        "Tipo": "Computador",
        "Modelo/Marca": "Bel Micro i5 2400 8GB ",
        "Número de série": "N/A",
        "Aquisição": "N/A",
        "Usuário Responsável": "Misael",
        "Localização": "Recebimento",
        "Endereço IP": "192.168.0.78",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Regular",
        "Última manutenção": "10/16/24",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-PC-031",
        "Tipo": "Computador",
        "Modelo/Marca": "Bel Micro AMD Athlon 3000G 8GB",
        "Número de série": "N/A",
        "Aquisição": "N/A",
        "Usuário Responsável": "Rodrigo Teixeira",
        "Localização": "Transporte",
        "Endereço IP": "192.168.0.52",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Regular",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-PC-032",
        "Tipo": "Computador",
        "Modelo/Marca": "Bel Micro i5 2400 16GB",
        "Número de série": "N/A",
        "Aquisição": "N/A",
        "Usuário Responsável": "Nicole",
        "Localização": "Caixa",
        "Endereço IP": "192.168.0.50",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Regular",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-PC-033",
        "Tipo": "Computador",
        "Modelo/Marca": "Bel Micro i5 2200 4GB",
        "Número de série": "N/A",
        "Aquisição": "N/A",
        "Usuário Responsável": "Lorena",
        "Localização": "Caixa",
        "Endereço IP": "192.168.0.75",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Regular",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-PC-034",
        "Tipo": "Computador",
        "Modelo/Marca": "Bel Micro AMD Athlon 3000G 8GB",
        "Número de série": "N/A",
        "Aquisição": "N/A",
        "Usuário Responsável": "Lorena",
        "Localização": "Transporte",
        "Endereço IP": "192.168.0.19",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Regular",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-PC-035",
        "Tipo": "Computador",
        "Modelo/Marca": "Bel Micro i7 2600 4GB",
        "Número de série": "N/A",
        "Aquisição": "N/A",
        "Usuário Responsável": "Weverton Oliveira",
        "Localização": "Transporte",
        "Endereço IP": "192.168.0.76",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Regular",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-PC-036",
        "Tipo": "Computador",
        "Modelo/Marca": "Bel Micro i5 12GB",
        "Número de série": "N/A",
        "Aquisição": "N/A",
        "Usuário Responsável": "Weverton Oliveira",
        "Localização": "Transporte",
        "Endereço IP": "192.168.0.32",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Regular",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": "Não possui modelo do processador cadastrado. Necessita ativação do windows"
    },
    {
        "ID": "REF-PC-037",
        "Tipo": "Computador",
        "Modelo/Marca": "i5-3570 12GB",
        "Número de série": "N/A",
        "Aquisição": "N/A",
        "Usuário Responsável": "Maicon Azevedo",
        "Localização": "Adm",
        "Endereço IP": "192.168.0.83",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Bom",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-PC-038",
        "Tipo": "Computador",
        "Modelo/Marca": "",
        "Número de série": "",
        "Aquisição": "",
        "Usuário Responsável": "",
        "Localização": "",
        "Endereço IP": "",
        "Status": "",
        "Valor": "",
        "Estado do equipamento": "",
        "Última manutenção": "",
        "Garantia": "",
        "Observações": ""
    },
    {
        "ID": "REF-RT-001",
        "Tipo": "Roteador",
        "Modelo/Marca": "Intelbras W6-1500",
        "Número de série": "N/A",
        "Aquisição": "N/A",
        "Usuário Responsável": "Weverton Oliveira",
        "Localização": "Adm",
        "Endereço IP": "",
        "Status": "Inativo",
        "Valor": "",
        "Estado do equipamento": "Ruim",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": "Temporareamente inativo, precisa ser \ndevidamente configurado"
    },
    {
        "ID": "REF-RT-002",
        "Tipo": "Roteador",
        "Modelo/Marca": "Multilaser AC1200",
        "Número de série": "RE018212608667",
        "Aquisição": "10/14/24",
        "Usuário Responsável": "Weverton Oliveira",
        "Localização": "Adm",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Bom",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": "Temporareamente inativo, precisa ser \ndevidamente configurado"
    },
    {
        "ID": "REF-SWC-001",
        "Tipo": "Switch de rede",
        "Modelo/Marca": "HP V1910-24G 24 Portas",
        "Número de série": "",
        "Aquisição": "10/15/24",
        "Usuário Responsável": "Weverton Oliveira",
        "Localização": "Adm",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Bom",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-SWC-002",
        "Tipo": "Switch de rede",
        "Modelo/Marca": "HP V1910-24G 24 Portas",
        "Número de série": "",
        "Aquisição": "10/16/24",
        "Usuário Responsável": "Weverton Oliveira",
        "Localização": "Adm",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Bom",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-SWC-003",
        "Tipo": "Switch de rede",
        "Modelo/Marca": "Intelbras SG 800Q+ 8 portas",
        "Número de série": "",
        "Aquisição": "",
        "Usuário Responsável": "Weverton Oliveira",
        "Localização": "Diretoria",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Bom",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    },
    {
        "ID": "REF-SWC-004",
        "Tipo": "Switch de rede",
        "Modelo/Marca": "Intelbras SG 2400 QR+ 24 portas",
        "Número de série": "",
        "Aquisição": "",
        "Usuário Responsável": "Weverton Oliveira",
        "Localização": "Adm",
        "Endereço IP": "",
        "Status": "Ativo",
        "Valor": "",
        "Estado do equipamento": "Bom",
        "Última manutenção": "-",
        "Garantia": "Não possui",
        "Observações": ""
    }
];

function searchAsset() {
    const ref = document.getElementById('searchRef').value.trim().toLowerCase();
    const resultTable = document.getElementById('resultTable');
    const resultBody = document.getElementById('resultBody');

    resultBody.innerHTML = '';
    resultTable.style.display = 'none';

    const asset = assets.find(a => 
        a.ID.toLowerCase() === ref ||
        a["Usuário Responsável"].toLowerCase() === ref
    );

    if (asset) {
        Object.entries(asset).forEach(([key, value]) => {
            const row = document.createElement('tr');
            row.innerHTML = `<td>${key}</td><td>${value}</td>`;
            resultBody.appendChild(row);
        });
        resultTable.style.display = 'table';
    } else {
        alert('Asset not found!');
    }
}
